-- Portfolio CMS schema for Supabase/PostgreSQL.
-- Run this once in Supabase SQL Editor, then configure the environment variables from .env.example.

create extension if not exists pgcrypto;

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  type text not null,
  summary text not null,
  result text not null default '',
  year text not null,
  role text,
  stack jsonb not null default '[]'::jsonb,
  visual text not null default 'architecture' check (visual in ('gallery','architecture','screenshot')),
  visual_label text,
  cover_image text,
  gallery jsonb,
  github_url text,
  live_url text,
  featured boolean not null default true,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  sort_order integer not null default 999,
  architecture jsonb,
  case_study jsonb not null default '{"overview":"","problem":"","approach":"","engineering":[]}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists projects_public_order_idx on public.projects(status, featured, sort_order);

create table if not exists public.site_settings (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.resume_versions (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  storage_path text not null unique,
  file_name text not null,
  file_size bigint not null,
  is_active boolean not null default false,
  uploaded_at timestamptz not null default now(),
  activated_at timestamptz
);

create unique index if not exists only_one_active_resume
  on public.resume_versions ((is_active)) where is_active = true;

create table if not exists public.contact_messages (
  id uuid primary key default gen_random_uuid(),
  reference text not null unique,
  type text not null,
  name text not null,
  email text not null,
  company text,
  message text not null,
  status text not null default 'new' check (status in ('new','read','replied','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists contact_messages_created_idx on public.contact_messages(created_at desc);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  event_type text not null,
  path text,
  project_slug text,
  referrer text,
  user_agent text,
  device_class text,
  browser text,
  os text,
  country text,
  ip_hash text,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_session_idx on public.analytics_events(session_id);
create index if not exists analytics_events_type_idx on public.analytics_events(event_type);

create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  file_name text not null,
  storage_path text not null unique,
  public_url text not null,
  mime_type text,
  size_bytes bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_idx on public.audit_logs(created_at desc);

insert into public.site_settings (id, data)
values ('site', '{
  "fullName": "Yash",
  "brandName": "YASH",
  "role": "Full-Stack & AI Engineer",
  "heroTitle": "I build software from idea to production.",
  "heroIntro": "Full-stack products, backend systems, AI-assisted developer tooling and applied machine learning — built with product judgement and production-minded engineering.",
  "availability": "Open to software engineering opportunities",
  "githubUrl": "https://github.com/YaswanthSai2003",
  "linkedinUrl": "",
  "email": "",
  "resumeUrl": ""
}'::jsonb)
on conflict (id) do nothing;

-- Seed the current selected work. Existing rows are not overwritten.
insert into public.projects
(slug,title,type,summary,result,year,role,stack,visual,visual_label,cover_image,gallery,github_url,live_url,featured,status,sort_order,architecture,case_study)
values
(
  'averlen','Averlen','Revenue intelligence platform',
  'A multi-tenant revenue intelligence product for hospitality teams to turn booking data into clearer operating and pricing decisions.',
  'Built the product end to end across data imports, analytics, pricing workflows, access control and AI-assisted insights.',
  '2026','Product design · Full-stack engineering',
  '["React","TypeScript","FastAPI","PostgreSQL","Redis","Docker"]'::jsonb,
  'gallery','Averlen / product preview','/projects/averlen-analytics.png',
  '[{"label":"Revenue analytics","description":"Revenue, bookings, booked nights, ADR, data quality and city performance in one portfolio view.","image":"/projects/averlen-analytics.png","alt":"Averlen revenue analytics dashboard"}]'::jsonb,
  'https://github.com/YaswanthSai2003/Averlen',null,true,'published',1,null,
  '{"overview":"Averlen brings property data, analytics, pricing workflows and AI-assisted insights into one multi-tenant product.","problem":"Revenue and operations data is often spread across files and tools, making it harder to understand performance quickly and make consistent pricing decisions.","approach":"I designed the product around a secure multi-tenant backend, structured data imports, analytics endpoints, pricing workflows and a frontend that keeps important actions close to the data.","engineering":["Multi-tenant data isolation","JWT authentication and role-based access","CSV preview, mapping and ingestion jobs","Revenue, occupancy and property analytics","Redis caching and backend reliability","Pricing recommendations and AI-assisted insights"],"decisions":[{"title":"Keep preview reads side-effect free","copy":"Pricing previews are separated from save/generate operations so exploration never creates history accidentally."},{"title":"Enforce tenant boundaries centrally","copy":"Organization scope is applied at the backend boundary instead of relying on frontend filtering."}]}'::jsonb
),
(
  'pr-review-agent','PR Review Agent','AI developer tooling',
  'An automated pull-request review system built around security, correctness, testing and maintainability checks.',
  'Designed to revalidate findings against the latest revision so comments do not become stale when a branch changes mid-review.',
  '2026','System design · AI engineering',
  '["Python","FastAPI","LLMs","GitHub","Pytest"]'::jsonb,
  'architecture','Review workflow',null,null,null,null,true,'published',2,
  '{"eyebrow":"PULL REQUEST / REVIEW PIPELINE","nodes":[{"label":"Pull request","description":"New or updated code"},{"label":"Revision snapshot","description":"Pin the exact revision"},{"label":"Review workers","description":"Security · correctness · tests · maintainability"},{"label":"Validator","description":"Reject weak or stale findings"},{"label":"Publish","description":"Comments valid for current code"}]}'::jsonb,
  '{"overview":"A review agent designed around a real production problem: pull requests can change while an automated review is still running.","problem":"If a branch changes mid-review, generated comments may point at code that has moved, been renamed or disappeared entirely.","approach":"The workflow snapshots the revision, runs specialist workers, validates the combined findings and checks the branch again before publishing feedback.","engineering":["Four specialist review workers plus a validator","Revision tracking and stale comment handling","Deterministic checks before LLM reasoning","Structured outputs and schema validation","Production-style evaluation cases"]}'::jsonb
),
(
  'object-detection','Object Detection','Applied machine learning',
  'A computer-vision workflow using Faster R-CNN for object localisation and classification.',
  'Covers the ML lifecycle from detection datasets and training to bounding-box inference and mAP evaluation.',
  '2026','Model training · Evaluation',
  '["PyTorch","Faster R-CNN","TorchMetrics","Python"]'::jsonb,
  'architecture','ML pipeline',null,null,'https://github.com/YaswanthSai2003/Object-detection-model',null,false,'published',4,
  '{"eyebrow":"COMPUTER VISION / MODEL PIPELINE","nodes":[{"label":"Dataset","description":"Images + labelled boxes"},{"label":"Preprocess","description":"Training-ready samples"},{"label":"Faster R-CNN","description":"Detection model"},{"label":"Inference","description":"Classes + bounding boxes"},{"label":"mAP","description":"Detection evaluation"}]}'::jsonb,
  '{"overview":"An applied computer-vision project focused on the complete object-detection workflow rather than only model inference.","problem":"Object detection must identify both what an object is and where it appears in an image, which needs different targets and evaluation from simple classification.","approach":"I prepared detection data, trained Faster R-CNN, visualised predictions and evaluated model quality using detection metrics such as mean average precision.","engineering":["Detection dataset preparation","Faster R-CNN training","Bounding-box inference","Confidence filtering and visualisation","TorchMetrics evaluation"]}'::jsonb
),
(
  'reading-platform','Reading Platform','Backend platform',
  'A backend-first reading platform with accounts, reading lists, reviews and administrative workflows.',
  'Combines secure authentication, permissions, pagination, rate limiting and user-content rules in a structured API.',
  '2026','API design · Security · Data modelling',
  '["Node.js","Express","PostgreSQL","Redis","JWT"]'::jsonb,
  'architecture','Backend architecture',null,null,'https://github.com/YaswanthSai2003/BookApi',null,true,'published',3,
  '{"eyebrow":"BACKEND / APPLICATION FLOW","nodes":[{"label":"Client","description":"Books, lists and reviews"},{"label":"REST API","description":"Application workflows"},{"label":"Auth + RBAC","description":"Identity and permissions"},{"label":"PostgreSQL","description":"Primary relational data"},{"label":"Redis","description":"Token and cache workflows"}]}'::jsonb,
  '{"overview":"A reading platform built around secure account and content-management workflows.","problem":"A reading-list application becomes significantly more complex once authentication, permissions, reviews, pagination and account security are introduced.","approach":"The platform separates admin and user responsibilities while keeping authentication, refresh tokens, reading lists and review workflows cleanly separated in the API.","engineering":["JWT access and refresh flow","Role-based permissions","Server-side pagination","Authentication rate limiting","Reading-list and review constraints","Password reset workflow"]}'::jsonb
),
(
  'compliance-tracker','Compliance Tracker','Full-stack application',
  'A responsive compliance workspace for clients, tasks, deadlines, filtering and lightweight analytics.',
  'Built the end-to-end task workflow with a React frontend and Node/Express API, then deployed it as a production web app.',
  '2026','Product engineering',
  '["React","Node.js","Express","Tailwind","Recharts"]'::jsonb,
  'architecture',null,null,null,'https://github.com/YaswanthSai2003/Mini-compliance-tracker','https://mini-compliance-tracker-1ka1.vercel.app/',false,'published',5,null,
  '{"overview":"A compact full-stack compliance tracker built around client work, task status, deadlines and responsive day-to-day usage.","problem":"Compliance work becomes difficult to scan once tasks are spread across clients and due dates without a clear view of priority and status.","approach":"I built a responsive client/task workflow with filters, CRUD actions, overdue states and analytics, backed by a Node/Express API.","engineering":["Responsive React UI","Task CRUD","Filtering and search","Analytics","Deployment"]}'::jsonb
),
(
  'finance-dashboard','Finance Dashboard','Frontend product UI',
  'An executive-style finance workspace for overview metrics, transactions, insights and role-aware views.',
  'Built a polished responsive interface with state management and data visualisation for a finance-oriented product brief.',
  '2026','Frontend engineering',
  '["React","Vite","Tailwind","Recharts","Zustand"]'::jsonb,
  'screenshot',null,null,null,null,'https://finance-dashboard-five-beige.vercel.app/',false,'published',6,null,
  '{"overview":"A frontend-focused finance dashboard designed around hierarchy, responsive layout and clear data visualisation.","problem":"Financial interfaces can become dense quickly, so the challenge was to keep key metrics, transactions and insights readable without flattening the information hierarchy.","approach":"I structured the experience around a clear overview, transaction detail, financial insights and role-aware interactions, using reusable React components and lightweight state management.","engineering":["Responsive layout","Reusable UI components","Zustand state","Recharts visualisation","Role-aware views"]}'::jsonb
),
(
  'smart-bookmarks','Smart Bookmarks','Next.js application',
  'A private bookmark manager with Google OAuth, Supabase Row Level Security and real-time cross-tab updates.',
  'Built authentication, per-user data isolation and real-time bookmark synchronisation using Next.js and Supabase.',
  '2026','Full-stack product engineering',
  '["Next.js","Supabase","PostgreSQL","OAuth","Realtime"]'::jsonb,
  'architecture',null,null,null,null,null,false,'published',7,null,
  '{"overview":"A focused full-stack app for saving private bookmarks and keeping them synchronised across sessions.","problem":"The interesting engineering work is not the bookmark form itself; it is authentication, data isolation and keeping UI state consistent when the same account is open in multiple tabs.","approach":"I used Google OAuth, Supabase Row Level Security and realtime database subscriptions so each user sees only their own data and changes propagate without a page refresh.","engineering":["Google OAuth","Row Level Security","Realtime subscriptions","Private per-user data","Next.js App Router"]}'::jsonb
)

on conflict (slug) do nothing;

-- Lock tables from direct anonymous access. The app talks to them server-side with the service-role key.
alter table public.projects enable row level security;
alter table public.site_settings enable row level security;
alter table public.resume_versions enable row level security;
alter table public.contact_messages enable row level security;
alter table public.analytics_events enable row level security;
alter table public.media_assets enable row level security;
alter table public.audit_logs enable row level security;

-- Storage buckets. portfolio-media is public for project screenshots; resumes remains private.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('portfolio-media','portfolio-media',true,8388608,array['image/png','image/jpeg','image/webp','image/gif']),
  ('resumes','resumes',false,5242880,array['application/pdf'])
on conflict (id) do nothing;
